name: Publish
on:
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install pnpm and turbo
              run: npm install -g pnpm turbo

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Build docs
              run: cd ./packages/core && pnpm docs

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: ./packages/core/docs
                  single-commit: true
